server {
    listen 80;
    server_name visionyx.lat www.visionyx.lat;
    location /.well-known/acme-challenge/ { root /var/www/html; }
    location / { return 301 https://visionyx.lat$request_uri; }
}

server {
    listen 80;
    server_name mail.visionyx.lat;
    location /.well-known/acme-challenge/ { root /var/www/html; }
    location / { return 301 https://mail.visionyx.lat$request_uri; }
}

server {
    listen 443 ssl;
    server_name www.visionyx.lat;
    ssl_certificate     /etc/letsencrypt/live/visionyx.lat/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/visionyx.lat/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    return 301 https://visionyx.lat$request_uri;
}

server {
    listen 443 ssl;
    server_name visionyx.lat;
    ssl_certificate     /etc/letsencrypt/live/visionyx.lat/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/visionyx.lat/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/visionyx;
    index index.html;

    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;

    location / { try_files $uri $uri/ =404; }
}

server {
    listen 443 ssl;
    server_name mail.visionyx.lat;
    ssl_certificate     /etc/letsencrypt/live/mail.visionyx.lat/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mail.visionyx.lat/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    client_max_body_size 50m;

    location / {
        proxy_pass http://127.0.0.1:8086;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
